DROP TABLE "ADMINISTRATORS";
DROP TABLE "CATEGORY";
DROP TABLE "ORDER_DETAILS";
--comment DELIVERYLOCATIONS if LOC_FEATURE not active
--DROP TABLE "DELIVERYLOCATIONS";
DROP TABLE "EXPENSES";
DROP TABLE "IMAGES";
DROP TABLE "PRODUCTS";
DROP TABLE "USER_AUTH";	
DROP SEQUENCE "SEQ1";
DROP SEQUENCE "USER_SEQ";
DROP PROCEDURE "ADD_ORDER";
